name: 'Setup Bun Environment'
description: 'Setup Bun and install dependencies'
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash