name: Short投稿
description: 技術的な知見をShortsとして投稿
labels: ["short"]
title: "[Short] "
body:
  - type: markdown
    attributes:
      value: |
        ## Shorts投稿

        ブログ記事にするには軽すぎるが、共有しておきたい技術的な知見を投稿します。

        **Issueタイトル**がそのままShortsのタイトルになります。
        このIssueを作成すると、自動的にMarkdownファイルが生成されPRが作成されます。

  - type: textarea
    id: content
    attributes:
      label: 本文
      description: Markdown形式で記述してください。コードブロック、リスト、リンクなどが使えます。
      placeholder: |
        簡潔に要点をまとめてください。

        ```js
        // コード例
        ```
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: 確認事項
      options:
        - label: 内容に誤りがないことを確認しました
          required: true
        - label: 公開しても問題ない内容であることを確認しました
          required: true
