/**
 * Diagram機能で使用するアイコンの一覧
 */

import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  BatteryWarning,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  Building,
  CheckCircle,
  CheckSquare,
  Clock,
  Code2,
  EyeOff,
  FileCode,
  FileSearch,
  FileText,
  Flag,
  GitMerge,
  HelpCircle,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Lock,
  type LucideIcon,
  Map as MapIcon,
  MessageCircle,
  MessageSquare,
  MessageSquareX,
  PenTool,
  Puzzle,
  RefreshCcw,
  Scale,
  Search,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Target,
  Users,
  UserX,
  Zap,
} from 'lucide-react';

/**
 * 使用可能なアイコン名の配列（真実の源）
 * Zodスキーマ生成で直接使用可能なタプル型
 */
export const ICON_NAMES = [
  'activity',
  'alert',
  'alertCircle',
  'alertTriangle',
  'arrow',
  'arrowRight',
  'batteryWarning',
  'bookOpen',
  'bot',
  'brain',
  'brainCircuit',
  'building',
  'check',
  'checkCircle',
  'checkSquare',
  'clock',
  'code2',
  'eyeOff',
  'fileCode',
  'fileSearch',
  'fileText',
  'flag',
  'gitMerge',
  'help',
  'layout',
  'layoutDashboard',
  'layoutTemplate',
  'lightbulb',
  'lock',
  'map',
  'message',
  'messageSquare',
  'messageSquareX',
  'pen',
  'puzzle',
  'refreshCcw',
  'scale',
  'search',
  'server',
  'settings',
  'shieldAlert',
  'shieldCheck',
  'smartphone',
  'target',
  'userX',
  'users',
  'zap',
] as const;

/**
 * アイコン名の型定義（ICON_NAMESから派生）
 */
export type IconName = (typeof ICON_NAMES)[number];

/**
 * アイコン名とLucideコンポーネントのマッピング
 * ICON_NAMESの型に基づいて型安全性を保証
 */
export const ICON_MAP: Record<IconName, LucideIcon> = {
  activity: Activity,
  alert: AlertCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrow: ArrowDown,
  arrowRight: ArrowRight,
  batteryWarning: BatteryWarning,
  bookOpen: BookOpen,
  bot: Bot,
  brain: Brain,
  brainCircuit: BrainCircuit,
  building: Building,
  check: CheckCircle,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  clock: Clock,
  code2: Code2,
  eyeOff: EyeOff,
  fileCode: FileCode,
  fileSearch: FileSearch,
  fileText: FileText,
  flag: Flag,
  gitMerge: GitMerge,
  help: HelpCircle,
  layout: Layout,
  layoutDashboard: LayoutDashboard,
  layoutTemplate: LayoutTemplate,
  lightbulb: Lightbulb,
  lock: Lock,
  map: MapIcon,
  message: MessageCircle,
  messageSquare: MessageSquare,
  messageSquareX: MessageSquareX,
  pen: PenTool,
  puzzle: Puzzle,
  refreshCcw: RefreshCcw,
  scale: Scale,
  search: Search,
  server: Server,
  settings: Settings,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  smartphone: Smartphone,
  target: Target,
  users: Users,
  userX: UserX,
  zap: Zap,
};
