name: Auto patch merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read # 検証結果を読み取るための権限を追加
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: meta # 依存関係のメタデータを取得
        uses: dependabot/fetch-metadata@v2 # 条件分岐でパッチバージョンかチェック
      - name: Wait for CI to succeed
        run: |
          # CIの完了を待つ
          gh pr checks "${GITHUB_HEAD_REF}" --watch
      - if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
